Pages/Authorization.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmileMate.Common;
using SmileMate.Common.Entities;
using MimeKit;
using MailKit.Net.Smtp;

namespace SmileMate.Pages
{
    public class Authorization : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly SmileMateContext _context;

        public Authorization(UserManager<User> userManager, SignInManager<User> signInManager, RoleManager<Role> roleManager, SmileMateContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostLoginAsync(string login, string password)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(login);
                if (user == null)
                {
                    return new JsonResult(new { success = false, message = "Пользователь не найден" });
                }

                var result = await _signInManager.PasswordSignInAsync(user.UserName, password, isPersistent: false, lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    var roles = await _userManager.GetRolesAsync(user);
                    return new JsonResult(new { success = true, redirectUrl = roles.Contains("Admin") ? Url.Page("/Index") : Url.Page("/Index") });
                }
                else if (result.IsLockedOut)
                {
                    return new JsonResult(new { success = false, message = "Аккаунт заблокирован" });
                }
                else
                {
                    return new JsonResult(new { success = false, message = "Неверный логин или пароль" });
                }
            }

            return new JsonResult(new { success = false, message = "Неверные данные ввода" });
        }



        //public async Task<IActionResult> OnPostLoginAsync(string login, string password)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var user = await _userManager.FindByNameAsync(login);
        //        if (user != null)
        //        {
        //            var result = await _signInManager.PasswordSignInAsync(user.UserName, password, isPersistent: false, lockoutOnFailure: false);

        //            if (result.Succeeded)
        //            {
        //                var roles = await _userManager.GetRolesAsync(user);
        //                if (roles.Contains("Admin"))
        //                {
        //                    return RedirectToPage("/Index");
        //                }
        //                else
        //                {
        //                    return RedirectToPage("/Index");
        //                }
        //            }
        //            else if (result.IsLockedOut)
        //            {
        //                ModelState.AddModelError(string.Empty, "User account locked out.");
        //            }
        //            else
        //            {
        //                ModelState.AddModelError(string.Empty, "Неверный логин или пароль");
        //            }
        //        }
        //        else
        //        {
        //            ModelState.AddModelError(string.Empty, "Неверный логин или пароль");
        //        }
        //    }

        //    return Page();
        //}


        //public async Task<IActionResult> OnPostLoginAsync(string login, string password)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var result = await _signInManager.PasswordSignInAsync(login, password, isPersistent: false, lockoutOnFailure: false);

        //        if (result.Succeeded)
        //        {
        //            var user = await _userManager.FindByNameAsync(login);
        //            if (user != null)
        //            {
        //                var roles = await _userManager.GetRolesAsync(user);

        //                if (roles.Contains("Admin"))
        //                {
        //                    return RedirectToPage("/Index");
        //                }
        //                else
        //                {
        //                    return RedirectToPage("/Index");
        //                }
        //            }
        //        }
        //        else if (result.IsLockedOut)
        //        {
        //            ModelState.AddModelError(string.Empty, "User account locked out.");
        //        }
        //        else
        //        {
        //            ModelState.AddModelError(string.Empty, "Invalid login attempt.");
        //        }
        //    }

        //    var errorList = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
        //    return NotFound($"Список ошибок: {string.Join(", ", errorList)}");
        //}


        public async Task<IActionResult> OnPostRegistrationAsync(string login, string password, string rb, string surname, string name, string patronymic)
        {

            if (rb == "doctor")
            {
                var doctor = new Doctor { UserName = login, Surname = surname, Name = name, Patronymic = patronymic };

                var result = await _userManager.CreateAsync(doctor, password);
                if (result.Succeeded)
                {
                    if (!await _roleManager.RoleExistsAsync("Doctor"))
                    {
                        await _roleManager.CreateAsync(new Role { Name = "Doctor" });
                    }

                    await _userManager.AddToRoleAsync(doctor, "Doctor");

                    return RedirectToPage("/Doctor");
                }
            }

            if (rb == "medicalworker")
            {
                var medicalworker = new User { UserName = login };

                var result = await _userManager.CreateAsync(medicalworker, password);
                if (result.Succeeded)
                {
                    if (!await _roleManager.RoleExistsAsync("MedicalWorker"))
                    {
                        await _roleManager.CreateAsync(new Role { Name = "MedicalWorker" });
                    }

                    await _userManager.AddToRoleAsync(medicalworker, "MedicalWorker");

                    return RedirectToPage("/Patient");
                }
            }
            var errorList = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
            return NotFound($"Список ошибок: {string.Join(", ", errorList)}");
        }

        public async Task<IActionResult> OnPostCreatePatientAsync(string username, string password, string surname, string name, string patronymic, string phonenumber, string date, string adress)
        {
            var patient = new Patient { UserName = username, Surname = surname, Name = name, Patronymic = patronymic, PhoneNumber = phonenumber, BirthdayDate = DateTime.Parse(date), Address = adress };

            var result = await _userManager.CreateAsync(patient, password);
            
            if (result.Succeeded)
            {
                if (!await _roleManager.RoleExistsAsync("Patient"))
                {
                    await _roleManager.CreateAsync(new Role { Name = "Patient" });
                }

                await _userManager.AddToRoleAsync(patient, "Patient");

                // Отправка электронного письма клиенту
                await SendEmailAsync(username, password);

                return RedirectToPage("/Patient");
            }

            var errorList = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
            return NotFound($"Список ошибок: {string.Join(", ", errorList)}");
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        { 
            await _signInManager.SignOutAsync();

            return RedirectToPage("/Index");
        }

        private readonly string _smtpServer = "smtp.gmail.com";
        private readonly int _smtpPort = 465;
        private readonly string _smtpUser = "serezha.tikhonov.2013@gmail.com";
        private readonly string _smtpPass = "onoewopmywkbkklk";
        private async Task SendEmailAsync(string username, string password)
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("SmileMate", _smtpUser));
            message.To.Add(new MailboxAddress(username, username));
            message.Subject = $"Вы зарегистрированы в стоматологической клинике";

            var builder = new BodyBuilder
            {
                HtmlBody = GenerateEmailBody(username, password)
            };

            message.Body = builder.ToMessageBody();

            using (var client = new SmtpClient())
            {
                await client.ConnectAsync(_smtpServer, _smtpPort, true);
                await client.AuthenticateAsync(_smtpUser, _smtpPass);
                await client.SendAsync(message);
                await client.DisconnectAsync(true);
            }
        }

        private string GenerateEmailBody(string username, string password)
        {
            var body = $"<div style=\"border-radius: 8px; background-color: #F2f2f2; padding: 20px 30px;\">" +
                       $"<p style=\"font-size: 32px; font-weight: 500;\">Ваш логин: {username}</p>" +
                       $"<p style=\"font-size: 32px; font-weight: 500;\">Ваш пароль: {password}</p>";

            return body;
        }
    }
}

Pages/Doctor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmileMate.Common;
using SmileMate.Common.Entities;

namespace SmileMate.Pages
{
    public class DoctorModel : PageModel
    {
        private readonly SmileMateContext _context;

        public DoctorModel(SmileMateContext context)
        {
            _context = context;
        }

        public List<Doctor> Doctors { get; set; }

        public async Task<IActionResult> OnGetAsync(string searchTerm)
        {
            IQueryable<Doctor> query = _context.Set<Doctor>();

            if(!String.IsNullOrEmpty(searchTerm))
            {
                searchTerm = searchTerm.ToLower();

                query = query.Where(d => d.Name.ToLower().Contains(searchTerm)
                    || d.Surname.ToLower().Contains(searchTerm)
                    || d.Patronymic.ToLower().Contains(searchTerm)
                    || d.UserName.ToLower().Contains(searchTerm));
            }

            Doctors = await query.ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? doctorid)
        {
            var doctor = await _context.Set<Doctor>()
                .Include(d => d.Receptions)
                .FirstOrDefaultAsync(d => d.Id == doctorid);

            if (doctor.Receptions.Count() != 0)
                return NotFound("Вы не можете удалить доктора, так как у него есть приемы");

            _context.Remove(doctor);
            await _context.SaveChangesAsync();

            return RedirectToPage();
        }
    }
}

Pages/DoctorCreate.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmileMate.Pages
{
    public class DoctorCreate : PageModel
    {
        private readonly ILogger<DoctorCreate> _logger;

        public DoctorCreate(ILogger<DoctorCreate> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/DoctorEdit.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmileMate.Common.Entities;
using SmileMate.Common;
using Microsoft.EntityFrameworkCore;

namespace SmileMate.Pages
{
    public class DoctorEdit : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly SmileMateContext _context;

        public DoctorEdit(UserManager<User> userManager, SmileMateContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public User CurrentDoctor { get; set; }

        public async Task<IActionResult> OnGet(int? doctorid)
        {
            if (doctorid is null)
                return NotFound("Id not provided");

            var user = await _context.Set<User>().FirstOrDefaultAsync(d => d.Id == doctorid);

            if(user is null)
                return NotFound($"Доктор с ID {doctorid} не найден");

            CurrentDoctor = user;

            return Page();
        }

        public async Task<IActionResult> OnPost(int? doctorid, string surname, string name, string patronymic)
        {
            var doctor = await _context.Set<User>().FirstOrDefaultAsync(d => d.Id == doctorid);

            if (doctor is null)
                return NotFound($"Доктор с ID {doctorid} не найден");

            if(!String.IsNullOrEmpty(surname))
                doctor.Surname = surname;

            if (!String.IsNullOrEmpty(name))
                doctor.Name = name;

            if (!String.IsNullOrEmpty(patronymic))
                doctor.Patronymic = patronymic;

            var result = await _userManager.UpdateAsync(doctor);

            return RedirectToPage("/Doctor", new { doctorid = doctorid });
        }
    }
}

Pages/DoctorPatient.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmileMate.Pages
{
    public class DoctorPatient : PageModel
    {
        private readonly ILogger<DoctorPatient> _logger;

        public DoctorPatient(ILogger<DoctorPatient> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/DoctorPatientCompleted.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmileMate.Common;
using SmileMate.Common.Entities;

namespace SmileMate.Pages
{
    public class DoctorPatientCompleted : PageModel
    {
        private readonly SmileMateContext _context;
        private readonly UserManager<User> _userManager;

        public DoctorPatientCompleted(SmileMateContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public List<Reception> Receptions { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var user = await _userManager.GetUserAsync(User);

            var receptions = await _context.Set<Reception>()
                .Include(r => r.Doctor)
                .Include(r => r.Client)
                .Where(r => r.Doctor.Id == user.Id)
                .ToListAsync();

            Receptions = receptions;

            return Page();
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SmileMate.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmileMate.Common;
using SmileMate.Common.Entities;

namespace SmileMate.Pages
{
    public class IndexModel : PageModel
    {
        private readonly SmileMateContext _context;

        public IndexModel(SmileMateContext context)
        {
            _context = context;
        }

        public List<User> Users { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Users = await _context.Set<User>().ToListAsync();

            return Page();
        }
    }
}

Pages/MedicalDisease.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmileMate.Common;
using SmileMate.Common.Entities;

namespace SmileMate.Pages
{
    public class MedicalDiseaseModel : PageModel
    {
        private readonly SmileMateContext _context;

        public MedicalDiseaseModel(SmileMateContext context)
        {
            _context = context;
        }

        [BindProperty]
        public MedicalHistory MedicalHistory { get; set; }

        public async Task<IActionResult> OnGet(int? mhid)
        {
            MedicalHistory = await _context.Set<MedicalHistory>()
                .Include(mh => mh.Reception).ThenInclude(r => r.Client)
                .Include(mh => mh.Reception).ThenInclude(r => r.Doctor)
                .FirstOrDefaultAsync(mh => mh.Id == mhid);

            return Page();
        }

        public async Task<IActionResult> OnPost(int? mhid, int? patientid)
        {
            var mhToDelete = await _context.Set<MedicalHistory>().FirstOrDefaultAsync(mh => mh.Id == mhid);

            _context.Remove(mhToDelete);

            await _context.SaveChangesAsync();

            return RedirectToPage("/MedicalHistory", new { patientid = patientid });
        }
    }
}

Pages/Authorization.cshtml
@page
@using SmileMate.Pages
@model Authorization
@{
}

Pages/Doctor.cshtml
@page
@model DoctorModel
@{
    ViewData["Title"] = "SmileMate - Врачи";
}

<section class="doctor">
        <div class="container">
            <div class="doctor-wrapper">
                <h1 class="doctor-title main-title">Врачи</h1>
                <div class="client-instrument instrument">
                    <form method="get" class="doctor-search search">
                    <div class="search-wrapper">
                        <input name="searchTerm" type="text" class="doctor-search--input search-input" placeholder="Поиск...">
                        <button type="submit" class="instrument-search--btn">
                            <img class="instrument-search--icon" src="/img/icon/search.svg">
                        </button>
                        </div>
                    </form>
                </div>
                
                <div class="doctor-table table">
                    <table class="doctor-table--wrapper table-wrapper">
                        <thead>
                            <tr>
                                <th>Фамилия</th>
                                <th>Имя</th>
                                <th>Отчество</th>
                                @* <th>Логин</th> *@
                                <th>Действие</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var doctor in Model.Doctors)
                            {
                            <tr>
                                <td>@doctor.Surname</td>
                                <td>@doctor.Name</td>
                                <td>@doctor.Patronymic</td>
                                @* <td>@doctor.UserName</td> *@
                                
                                <td>
                                    <a href="/DoctorEdit?doctorid=@doctor.Id" class="table-btn table-btn--info second-btn">Редактировать</a>
                                </td>
                                <td>
                                    <form method="post">
                                        <input type="hidden" name="doctorid" value="@doctor.Id"/>
                                        <button class="table-btn table-btn--delete second-btn">Удалить</button>
                                    </form>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

Pages/DoctorCreate.cshtml
@page
@model DoctorCreate
@{
    ViewData["Title"] = "SmileMate - Заведение доктора";
}

    <h1 class="doctor-create--title main-title">Создание доктора</h1>
    <section class="doctor-create create">
        <div class="container">
            <div class="create-wrapper form-wrapper">
                <div class="create-form form doctor-create">
                    <form action="" class="">
                        <label class="input-label">Фамилия *</label>
                            <input type="text" class="input-surname form-input input" placeholder="Введите данные...">
                            <label class="input-label">Имя *</label>
                            <input type="text" class="input-name form-input input" placeholder="Введите данные...">
                            <label class="input-label">Отчество *</label>
                            <input type="text" class="input-patronymic form-input input" placeholder="Введите данные...">
                            <label class="input-label">Электронная почта * </label>
                            <input type="text" class="input-emial form-input input" placeholder="Введите данные...">
                        <div class="form-btn">
                            <a href="" class="btn-reg main-btn doctor-create--btn">Зарегистрировать</a>
                        </div>
                    </form>
                </div>

                <div class="doctor-create-back-btn">
                    <button class="create-back-btn back-btn doctor-create--back">
                        <svg class="back-btn--icon" width="29" height="19" viewBox="0 0 29 19"  xmlns="http://www.w3.org/2000/svg">
                            <path d="M14.3333 5.07867V1.66667C14.3327 1.40318 14.2282 1.1457 14.0328 0.926695C13.8375 0.707689 13.5601 0.536953 13.2355 0.436003C12.911 0.335053 12.5539 0.308406 12.2092 0.359421C11.8645 0.410435 11.5477 0.536829 11.2986 0.722672L0.111084 9.00001L11.2986 17.276C11.4634 17.4003 11.6592 17.4989 11.8749 17.5661C12.0906 17.6334 12.3219 17.6681 12.5555 17.6681C12.7891 17.6681 13.0205 17.6334 13.2362 17.5661C13.4519 17.4989 13.6477 17.4003 13.8124 17.276C13.9776 17.1523 14.1086 17.0053 14.198 16.8436C14.2874 16.6818 14.3334 16.5084 14.3333 16.3333V13.0147C19.2222 13.1053 24.5644 13.7693 28.5555 18.3333V17C28.5555 10.8227 22.3333 5.74267 14.3333 5.07867Z"/>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </section>

Pages/DoctorEdit.cshtml
@page
@model DoctorEdit
@{
    ViewData["Title"] = "SmileMate - Редактирование доктора";
}

    <h1 class="doctor-create--title main-title">Редактирование доктора</h1>
    <section class="doctor-create create">
        <div class="container">
            <div class="create-wrapper form-wrapper">
                <div class="create-form form doctor-create">
                    <form method="post" class="">
                        <label class="input-label">Фамилия</label>
                        <input name="surname" type="text" class="input-surname form-input input" value="@Model.CurrentDoctor.Surname">
                        <label class="input-label">Имя</label>
                    <input name="name" type="text" class="input-name form-input input" value="@Model.CurrentDoctor.Name">
                        <label class="input-label">Отчество</label>
                    <input name="patronymic" type="text" class="input-patronymic form-input input" value="@Model.CurrentDoctor.Patronymic">
                        <div class="form-btn">
                            <button type="submit" class="btn-reg main-btn doctor-create--btn">Редактировать</button>
                        </div>
                    </form>
                </div>
                <div class="doctor-create-back-btn">
                    <a asp-page="/Doctor" class="create-back-btn back-btn doctor-create--back">
                        <svg class="back-btn--icon" width="29" height="19" viewBox="0 0 29 19"  xmlns="http://www.w3.org/2000/svg">
                            <path d="M14.3333 5.07867V1.66667C14.3327 1.40318 14.2282 1.1457 14.0328 0.926695C13.8375 0.707689 13.5601 0.536953 13.2355 0.436003C12.911 0.335053 12.5539 0.308406 12.2092 0.359421C11.8645 0.410435 11.5477 0.536829 11.2986 0.722672L0.111084 9.00001L11.2986 17.276C11.4634 17.4003 11.6592 17.4989 11.8749 17.5661C12.0906 17.6334 12.3219 17.6681 12.5555 17.6681C12.7891 17.6681 13.0205 17.6334 13.2362 17.5661C13.4519 17.4989 13.6477 17.4003 13.8124 17.276C13.9776 17.1523 14.1086 17.0053 14.198 16.8436C14.2874 16.6818 14.3334 16.5084 14.3333 16.3333V13.0147C19.2222 13.1053 24.5644 13.7693 28.5555 18.3333V17C28.5555 10.8227 22.3333 5.74267 14.3333 5.07867Z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </section>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "SmileMate - Главная страница";
}



<section class="index">
    <h1 class="index-title main-title">Добро пожаловать!</h1>
    @if(!User.Identity.IsAuthenticated){
        <p class="index-subtitle second-title">Необходимо авторизоваться.</p>
    }
</section>

Pages/PatientCreate.cshtml
@page
@model PatientCreate
@{
    ViewData["Title"] = "SmileMate - Регистрация клиента";
}

    <h1 class="client-create--title main-title">Регистрация клиента</h1>
    <section class="client-create create">
        <div class="container">
            <div class="create-wrapper form-wrapper">
                <div class="create-form form">
                    <form method="post" asp-page="/Authorization" asp-page-handler="CreatePatient" class="">
                        <div class="form-inputs">
                            <div class="inputs-left">
                                <label class="input-label">Фамилия</label>
                                <input required name="surname" type="text" class="input-surname form-input input" placeholder="Введите данные...">
                                <label class="input-label">Имя</label>
                                <input required name="name" type="text" class="input-name form-input input" placeholder="Введите данные...">
                                <label class="input-label">Отчество</label>
                                <input required name="patronymic" type="text" class="input-patronymic form-input input" placeholder="Введите данные...">
                            </div>
                            <div class="inputs-rigth">
                                <label class="input-label">Номер телефона</label>
                                <input autocomplete="off" required name="phonenumber" type="text" class="input-number form-input input" id="phone" placeholder="+7(___) ___-__-__">
                                <label class="input-label">Дата рождения</label>
                                <input required name="date" type="date" class="input-date form-input input" id="birthdate" placeholder="Введите данные...">
                                <label autocomplete="off"class="input-label">Адрес</label>
                                <input required name="adress" type="text" class="input-address form-input input" placeholder="Введите данные...">
                            </div>
                        </div>
                        <p class="form-label form-account">Данные для авторизации клиента</p>
                        <div class="inputs-bottom">
                            <div class="input-bottom--item input-bottom--email">
                                <label required class="input-label">Электронная почта</label>
                                <input id="email" oninput="validateEmail()" name="username" type="text" class="input-email patient-email form-input input" placeholder="Введите данные...">
                                <span id="error-message" class="error"></span>
                            </div>
                            <div class="input-bottom--item">
                                <div class="password-wrapper password-wrapper--profile">
                                    <label class="input-label">Пароль</label>
                                    <input required name="password" type="password" class="input-password patient-password form-input input" placeholder="Введите  пароль...">
                                    <button type="button" class="toggle-password toggle-password--patient" onclick="togglePassword()">
                                        <svg id="eye-icon" width="22" height="15" viewBox="0 0 22 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M11 4.5C10.2044 4.5 9.44129 4.81607 8.87868 5.37868C8.31607 5.94129 8 6.70435 8 7.5C8 8.29565 8.31607 9.05871 8.87868 9.62132C9.44129 10.1839 10.2044 10.5 11 10.5C11.7956 10.5 12.5587 10.1839 13.1213 9.62132C13.6839 9.05871 14 8.29565 14 7.5C14 6.70435 13.6839 5.94129 13.1213 5.37868C12.5587 4.81607 11.7956 4.5 11 4.5ZM11 12.5C9.67392 12.5 8.40215 11.9732 7.46447 11.0355C6.52678 10.0979 6 8.82608 6 7.5C6 6.17392 6.52678 4.90215 7.46447 3.96447C8.40215 3.02678 9.67392 2.5 11 2.5C12.3261 2.5 13.5979 3.02678 14.5355 3.96447C15.4732 4.90215 16 6.17392 16 7.5C16 8.82608 15.4732 10.0979 14.5355 11.0355C13.5979 11.9732 12.3261 12.5 11 12.5ZM11 0C6 0 1.73 3.11 0 7.5C1.73 11.89 6 15 11 15C16 15 20.27 11.89 22 7.5C20.27 3.11 16 0 11 0Z" />
                                        </svg>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="form-btn">
                            <button type="submit" id="submit-button" class="btn-reg patient-create--btn main-btn">Зарегистрировать</button>
                        </div>
                    </form>
                </div>

                <div class="client-create-back-btn">
                    <a asp-page="/Patient" class="create-back-btn back-btn">
                        <svg class="back-btn--icon" width="29" height="19" viewBox="0 0 29 19"  xmlns="http://www.w3.org/2000/svg">
                            <path d="M14.3333 5.07867V1.66667C14.3327 1.40318 14.2282 1.1457 14.0328 0.926695C13.8375 0.707689 13.5601 0.536953 13.2355 0.436003C12.911 0.335053 12.5539 0.308406 12.2092 0.359421C11.8645 0.410435 11.5477 0.536829 11.2986 0.722672L0.111084 9.00001L11.2986 17.276C11.4634 17.4003 11.6592 17.4989 11.8749 17.5661C12.0906 17.6334 12.3219 17.6681 12.5555 17.6681C12.7891 17.6681 13.0205 17.6334 13.2362 17.5661C13.4519 17.4989 13.6477 17.4003 13.8124 17.276C13.9776 17.1523 14.1086 17.0053 14.198 16.8436C14.2874 16.6818 14.3334 16.5084 14.3333 16.3333V13.0147C19.2222 13.1053 24.5644 13.7693 28.5555 18.3333V17C28.5555 10.8227 22.3333 5.74267 14.3333 5.07867Z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </section>